image: aaronang/miniconda3-jdk

before_script:
  - conda env create --force --file environment.yml
  - source activate hydra
  - apt-get update
  - apt-get -y install xvfb

test:
  script:
    - tar -xzvf bin/ScienceBirds_Linux.tar.gz -C bin/
    - tar -xzvf data/science_birds/ANU_Levels.tar.gz -C data/science_birds/
    - cp -r data/science_birds/Levels/novelty_level_0 bin/sciencebirds_linux/sciencebirds_linux_Data/StreamingAssets/Levels/
    - python -m pytest
