image: aaronang/miniconda3-jdk

before_script:
  - conda env create --force --file environment.yml
  - source activate hydra
  - apt-get -y install xvfb

test:
  script:
    - tar -xzvf bin/ScienceBirds_Linux.tar.gz -C bin/
    - python -m pytest
