image: aaronang/miniconda3-jdk

before_script:
  - conda env create --force --file environment.yml
  - source activate hydra
  - pip install .
  - apt-get update

test:
  script:
    - unzip -q -o bin/linux.zip -d ./bin
    - unzip -q -o bin/pal.zip -d ./bin
    - ./bin/setup_polycraft.sh
    - tar -xvzf data/science_birds/perception/object_classification.tar.gz
    - export PYTHONPATH=".:./worlds/science_birds_interface/"
    - python -m pytest
