image: aaronang/miniconda3-jdk

before_script:
  - conda env create --force --file environment.yml
  - source activate hydra
  - pip install .
  - apt-get update

test:
  script:
    - unzip -o bin/linux.zip -d ./bin
    - export PYTHONPATH=".:./worlds/science_birds_interface/"
    - python -m pytest
