image: continuumio/miniconda3:4.7.12

before_script:
  - conda env create --force --file environment.yml
  - source activate hydra

test:
  script:
    - tar -xzvf bin/ScienceBirds_Linux.tar.gz -C bin/
    - python -m pytest
