version: '3'
services:
  docker-host:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure
  hydra:
    depends_on:
      - docker-host
    build: .
    image: hydra
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/bin/docker:/usr/bin/docker"
      - "/usr/local/bin/docker:/usr/local/bin/docker"
    environment:
      - DOCKER=1
