name: hydra
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - pip
  - pytest
  - numpy
  - shapely
  - pillow
  - opencv
  - scipy
  - matplotlib
  - scikit-image
  - scikit-learn
  - pandas
  - func_timeout
  - gym
  - python-dateutil=2.8.1
  - psutil
  - pytz
  - pytorch=1.7.0
  - torchvision=0.8.1
  - shortuuid
  - seaborn
  - certifi==2020.4.5.2
  - cffi==1.14.0
  - chardet==3.0.4
  - cloudpickle==1.3.0
  - cycler==0.10.0
  - descartes==1.1.0
  - filelock==3.0.12
  - future==0.18.2
  - idna==2.9
  - isodate==0.6.0
  - kiwisolver==1.2.0
  - mizani==0.6.0
  - msrest==0.6.14
  - oauthlib==3.1.0
  - patsy==0.5.1
  - psutil==5.7.0
  - pycparser==2.20
  - pyglet==1.5.0
  - pyodbc==4.0.30
  - pyparsing==2.4.7
  - pytz==2020.1
  - requests==2.23.0
  - requests-oauthlib==1.3.0
  - six==1.14.0
  - tornado==6.0.4
  - urllib3==1.25.9
  - pip:
      - pika==1.1.0
      - astar==0.9
      - blosc==1.10.4
      - pybullet==3.1.7
      - pyinterval==1.2.0
      - -e .
