name: hydra
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pytest
  - numpy
  - shapely
  - pillow
  - opencv
  - scipy
  - matplotlib
  - scikit-image
  - scikit-learn
  - pandas
  - func_timeout
  - gym
  - python-dateutil=2.8.1
  - psutil
  - pytz
  - pytorch
  - pip:
      - pika==1.1.0

