name: hydra
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pytest
  - numpy
  - shapely
  - pillow
  - opencv
  - scipy
  - matplotlib
  - scikit-image
  - pip:
      - -e .

