(define (problem angry_birds_prob)
(:domain angry_birds_scaled)
(:objects redBird_0 - bird pig_4 - pig wood_2 - wood_block wood_3 - wood_block dummy_ice - ice_block dummy_stone - stone_block dummy_platform - platform )
(:init (= (gravity) 134.2)
    (= (active_bird) 0)
    (= (angle) 0)
    (= (angle_rate) 20)
    (not (angle_adjusted))
    (not (bird_dead redBird_0))
    (not (bird_released redBird_0))
    (= (x_bird redBird_0) 192)
    (= (y_bird redBird_0) 29)
    (= (v_bird redBird_0) 270)
    (= (vy_bird redBird_0) 0)
    (= (bird_id redBird_0) 0)
    (not (wood_destroyed wood_2))
    (= (x_wood wood_2) 445.0)
    (= (y_wood wood_2) 25.0)
    (= (wood_height wood_2) 12.0)
    (= (wood_width wood_2) 24.0)
    (not (wood_destroyed wood_3))
    (= (x_wood wood_3) 447.0)
    (= (y_wood wood_3) 13.0)
    (= (wood_height wood_3) 13.0)
    (= (wood_width wood_3) 24.0)
    (not (pig_dead pig_4))
    (= (x_pig pig_4) 449.0)
    (= (y_pig pig_4) 53.0)
    (= (margin_pig pig_4) 21)
)
(:goal (and  (pig_dead pig_4)))
(:metric minimize(total-time))
)
