(define(problem cartpole_prob)
(:domain cartpole-initial-bhaskara)
(:objects dummy_obj - dummy )
(:init 	(= (m_cart)  1.0)
	(= (friction_cart)  0.0)
	(= (l_pole)  0.5)
	(= (m_pole)  0.1)
	(= (friction_pole)  0.0)
	(= (force_mag)  10.0)
	(= (inertia)  1.0)
	(= (elapsed_time)  0.0)
	(= (gravity)  4.9)
	(= (time_limit)  3.2)
	(= (angle_limit)  0.205)
	(= (x_limit)  2.4)
	(ready)
	(cart_available)
	(= (x)  -0.11147)
	(= (x_dot)  -0.4221)
	(= (theta)  0.08031)
	(= (theta_dot)  0.29993)
	(= (F)  10.0)
	(= (x_ddot)  9.7232)
	(= (theta_ddot)  -13.94815)
)
(:goal (and  (not (total_failure) )  (= (elapsed_time)  (time_limit) ) ))
(:metric minimize(total-time))
)
