(define (problem angry_birds_prob)
(:domain angry_birds_scaled)
(:objects redBird_5 - bird pig_9 - pig wood_7 - block wood_8 - block dummy_platform - platform )
(:init (= (gravity) 139.0)
    (= (angle) 0)
    (= (angle_rate) 10)
    (bird_in_slingshot)
    (not (angle_adjusted))
    (not (bird_dead redBird_5))
    (not (bird_released redBird_5))
    (= (x_bird redBird_5) 177.0)
    (= (y_bird redBird_5) 36.0)
    (= (v_bird redBird_5) 280)
    (= (vy_bird redBird_5) 0)
    (not (block_destroyed wood_7))
    (= (x_block wood_7) 528)
    (= (y_block wood_7) 25)
    (= (block_height wood_7) 12)
    (= (block_width wood_7) 23)
    (not (block_destroyed wood_8))
    (= (x_block wood_8) 530)
    (= (y_block wood_8) 12)
    (= (block_height wood_8) 12)
    (= (block_width wood_8) 24)
    (not (pig_dead pig_9))
    (= (x_pig pig_9) 531)
    (= (y_pig pig_9) 52)
    (= (margin_pig pig_9) 14.0)
)
(:goal (and  (not (bird_dead redBird_5)) (pig_dead pig_9)))
(:metric minimize(total-time))
)
