(define (problem angry_birds_prob)
(:domain angry_birds_scaled)
(:objects redBird_0 - bird pig_10 - pig ice_4 - block dummy_platform - platform )
(:init (= (gravity) 134.2)
    (= (active_bird) 0)
    (= (angle) 0)
    (= (angle_rate) 40)
    (= (ground_damper) 0.4)
    (not (angle_adjusted))
    (not (bird_released redBird_0))
    (= (x_bird redBird_0) 195)
    (= (y_bird redBird_0) 29)
    (= (v_bird redBird_0) 270)
    (= (vy_bird redBird_0) 0)
    (= (vx_bird redBird_0) 0)
    (= (bird_id redBird_0) 0)
    (not (pig_dead pig_10))
    (= (x_pig pig_10) 376.0)
    (= (y_pig pig_10) 53.0)
    (= (pig_radius pig_10) 21)
    (= (x_block ice_4) 372.0)
    (= (y_block ice_4) 24.0)
    (= (block_height ice_4) 12.0)
    (= (block_width ice_4) 24.0)
    (= (block_life ice_4) 132.5)
    (= (block_mass ice_4) 0.125)
)
(:goal (and (angle_adjusted)))
(:metric minimize(total-time))
)
